services:
  nginx:
    image: nginx:tradesoft
    build: 
      context: ./nginx
      additional_contexts:
        scripts: ./scripts
    ports:
      - "80:80"
    volumes:
      - /srv/nginx/conf:/etc/nginx
      - /srv/nginx/logs:/var/log/nginx
