services:
  apache:
    image: apache:tradesoft
    build:
      context: ./apache
      additional_contexts:
        scripts: ./scripts
    networks:
      default:
        aliases:
          - domain1.local
          - domain2.local
    volumes:
      - /srv/apache/conf:/etc/apache2
      - /srv/apache/logs:/var/log/apache2
      - /srv/www/html:/var/www/html
