services:
  prometheus:
    image: prometheus:tradesoft
    build:
      context: ./prometheus
      additional_contexts:
        scripts: ./scripts
    volumes:
      - /srv/prometheus/conf:/etc/prometheus
