services:
  mysql:
    image: mysql:tradesoft
    build: 
      context: ./mysql
      additional_contexts:
        scripts: ./scripts
    volumes:
      - /srv/mysql/conf:/etc/my.cnf.d
      - /srv/mysql/logs:/var/log/mysql
      - /srv/mysql/data:/var/lib/mysql
