services:
  nginx:
    image: nginx:tradesoft
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - apache
      - mysql
    volumes:
      - nginx-conf:/etc/nginx:ro
      - nginx-logs:/var/log/nginx
  apache:
    image: apache:tradesoft
    build: ./apache
    volumes:
      - /srv/apache/conf:/etc/apache2
      - /srv/apache/logs:/var/log/apache2
      - /srv/www/html:/var/www/html
  mysql:
    image: mysql:tradesoft
    build: ./mysql
    volumes:
      - /srv/mysql/conf:/etc/my.cnf.d
      - /srv/mysql/logs:/var/log/mysql
      - /srv/mysql/data:/var/lib/mysql
  prometheus:
    image: prometheus:tradesoft
    build: ./prometheus
    volumes:
      - /srv/prometheus/conf:/etc/prometheus
  grafana:
    image: grafana:tradesoft
    build: ./grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      -  /srv/grafana/conf:/etc/grafana
      
volumes:
  nginx-conf:
    driver: local
    driver_opts:
      device: /srv/nginx/conf
  nginx-logs:
    driver: local
    driver_opts:
      type: none
      device: /srv/nginx/logs
      o: bind
  apache-conf:
    driver: local
    driver_opts:
      type: none
      device: /srv/apache/conf
      o: bind
