services:
  nginx:
    image: nginx:tradesoft
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - nginx-conf:/etc/nginx
      - nginx-logs:/var/log/nginx

volumes:
  nginx-conf:
    driver: local
    driver_opts:
      device: /srv/nginx/conf
  nginx-logs:
    driver: local
    driver_opts:
      type: none
      device: /srv/nginx/logs
      o: bind
