services:
  apache:
    image: apache:tradesoft
    build: 
      context: ./apache
      additional_contexts:
        scripts: ./scripts
    volumes:
      - /srv/apache/conf:/etc/apache2
      - /srv/apache/logs:/var/log/apache2
      - /srv/www/html:/var/www/html
