services:
  grafana:
    image: grafana:tradesoft
    build:
      context: ./grafana
      additional_contexts:
        scripts: ./scripts
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - /srv/grafana/conf:/etc/grafana
