services:
  prometheus:
    image: prometheus:tradesoft
    build: ./prometheus
    volumes:
      - /srv/prometheus/conf:/etc/prometheus
#      - prometheus-conf:/etc/prometheus

#volumes:
#  prometheus-conf:
#    driver: local
#    driver_opts:
#      device: /srv/prometheus/conf
#      type: none
#      o: bind
