services:
  nginx:
    image: nginx:tradesoft
    build: ./nginx
    depends_on:
      - apache
      - mysql
    ports:
      - "80:80"
    volumes:
      - /srv/nginx/conf:/etc/nginx
      - /srv/nginx/logs:/var/log/nginx
#      - nginx-conf:/etc/nginx
#      - nginx-logs:/var/log/nginx

#volumes:
#  nginx-conf:
#    driver: local
#    driver_opts:
#      device: /srv/nginx/conf
#      type: none
#      o: bind
#  nginx-logs:
#    driver: local
#    driver_opts:
#      device: /srv/nginx/logs
#      type: none
#      o: bind
