mkdir -p /srv/apache/conf
mkdir -p /srv/apache/logs
mkdir -p /srv/www
mkdir -p /srv/nginx/conf
mkdir -p /srv/nginx/logs
mkdir -p /srv/mysql/conf
mkdir -p /srv/mysql/logs
mkdir -p /srv/mysql/data
mkdir -p /srv/grafana
mkdir -p /srv/prometheus
